### ISSUE TITLE
Request ng14 support

### ISSUE THREAD

**Issue by dineshkumar02** [bluehalo/ngx-leaflet-d3#44]
Hi,

Currently, we are facing below error while build this library with ng14.

npm ERR! While resolving: tauri-app@0.0.0
npm ERR! Found: @angular/common@14.2.12
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"13" from @asymmetrik/ngx-leaflet-d3@13.0.1
npm ERR! node_modules/@asymmetrik/ngx-leaflet-d3
npm ERR!   @asymmetrik/ngx-leaflet-d3@"^13.0.1" from the root project

Would you help us to give ng14 supported version of the same please.

Thanks for your wonderful efforts.

Regards,
Dinesh

**Comment by reblace** [comment]
Published v14 compatible with Angular14

**Comment by dineshtessell** [comment]
Thank you @reblace
